LanchesMac/Models/Pedido.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LanchesMac.Models
{
    public class Pedido
    {
        public int PedidoId { get; set; }

        [Required(ErrorMessage = "Informe o nome")]
        [StringLength(50)]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Informe o sobrenome")]
        [StringLength(50)]
        public string Sobrenome { get; set; }

        [Required(ErrorMessage = "Informe o seu endereço")]
        [StringLength(100)]
        [Display(Name = "Endereço")]
        public string Endereco1 { get; set; }

        [StringLength(100)]
        [Display(Name = "Complemento")]
        public string Endereco2 { get; set; }

        [Required(ErrorMessage = "Informe o seu CEP")]
        [Display(Name = "CEP")]
        [StringLength(10, MinimumLength = 8)]
        public string Cep { get; set; }

        [StringLength(10)]
        public string Estado { get; set; }

        [StringLength(50)]
        public string Cidade { get; set; }

        [Required(ErrorMessage = "Informe o seu telefone")]
        [StringLength(25)]
        [DataType(DataType.PhoneNumber)]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Informe o email.")]
        [StringLength(50)]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|""(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*"")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])",
            ErrorMessage = "O email não possui um formato correto")]
        public string Email { get; set; }

        [ScaffoldColumn(false)]
        [Column(TypeName = "decimal(18,2)")]
        [Display(Name = "Total do Pedido")]
        public decimal PedidoTotal { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Itens no Pedido")]
        public int TotalItensPedido { get; set; }

        [Display(Name = "Data do Pedido")]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy hh:mm}", ApplyFormatInEditMode = true)]
        public DateTime PedidoEnviado { get; set; }

        [Display(Name = "Data Envio Pedido")]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy hh:mm}", ApplyFormatInEditMode = true)]
        public DateTime? PedidoEntregueEm { get; set; }

        public List<PedidoDetalhe> PedidoItens { get; set; }
    }
}

LanchesMac/Controllers/CarrinhoCompraController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal(),
            };

            return View(carrinhoCompraVM);
        }

        [Authorize]
        public IActionResult AdicionarItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p => p.LancheId == lancheId);

            if(lancheSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult RemoverItemDoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p => p.LancheId == lancheId);

            if(lancheSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }
    }
}

LanchesMac/Controllers/PedidoController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public PedidoController(IPedidoRepository pedidoRepository, CarrinhoCompra carrinhoCompra)
        {
            _pedidoRepository = pedidoRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Checkout(Pedido pedido)
        {
            int totalItensPedido = 0;
            decimal precoTotalPedido = 0.0m;

            //Obtém os itens do carrinho de compra do cliente
            List<CarrinhoCompraItem> items = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = items;

            //Verifica se existem itens de pedido
            if(_carrinhoCompra.CarrinhoCompraItems.Count == 0)
            {
                ModelState.AddModelError("", "Seu carrinho está vazio, não vai ficar com fome né?");
            }

            //Calcula o total de itens e o total do pedido
            foreach(var item in items)
            {
                totalItensPedido += item.Quantidade;
                precoTotalPedido += (item.Lanche.Preco * item.Quantidade);
            }

            //Atribui os valores obtidos ao pedido
            pedido.TotalItensPedido = totalItensPedido;
            pedido.PedidoTotal = precoTotalPedido;

            //Valida os dados do pedido
            if(ModelState.IsValid)
            {
                //Cria o pedido e os detalhes
                _pedidoRepository.CriarPedido(pedido);

                //Define mensagens ao cliente
                ViewBag.CheckoutCompletoMensagem = "Obrigado pelo seu pedido!";
                ViewBag.TotalPedido = _carrinhoCompra.GetCarrinhoCompraTotal();

                //Limpa o carrinho do cliente
                _carrinhoCompra.LimparCarrinho();

                //Exibe a view com dados do cliente e do pedido
                return View("~/Views/Pedido/CheckoutCompleto.cshtml", pedido);
            }

            return View(pedido);
        }
    }
}

LanchesMac/Views/Pedido/Checkout.cshtml
@model Pedido

<h3>Você está a um passo de completar seu pedido!</h3>
<hr/>
<form asp-action="Checkout" method="post" class="form-horizontal" role="form">
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Sobrenome" class="control-label"></label>
            <input asp-for="Sobrenome" class="form-control" />
            <span asp-validation-for="Sobrenome" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="Endereco1" class="control-label"></label>
            <input asp-for="Endereco1" class="form-control" />
            <span asp-validation-for="Endereco1" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Endereco2" class="control-label"></label>
            <input asp-for="Endereco2" class="form-control" />
            <span asp-validation-for="Endereco2" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="Cep" class="control-label"></label>
            <input asp-for="Cep" class="form-control" />
            <span asp-validation-for="Cep" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Cidade" class="control-label"></label>
            <input asp-for="Cidade" class="form-control" />
            <span asp-validation-for="Cidade" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Estado" class="control-label"></label>
            <input asp-for="Estado" class="form-control" />
            <span asp-validation-for="Estado" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="Telefone" class="control-label"></label>
            <input asp-for="Telefone" class="form-control" />
            <span asp-validation-for="Telefone" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <br/>

    <div class="row">
        <div class="form-group col-md-3">
            <input class="btn btn-success" type="submit" value="Concluir Pedido" />
        </div>
        &nbsp;

        <div class="form-group col-md-3">
            <a class="btn btn-outline-info" asp-controller="CarrinhoCompra" asp-action="Index">Retornar ao Carrinho</a>
        </div>
    </div>
</form>

LanchesMac/Views/Pedido/CheckoutCompleto.cshtml
@model Pedido

<div class="container">

    <div class="jumbotron">
        <h2>@ViewBag.CheckoutCompletoMensagem</h2>
    </div>

    <div class="card">
        <div class="card-body">
            <p>Cliente: <strong>@Model.Nome</strong>
            <p>Data do Pedido: <strong>@Model.PedidoEnviado</strong>
            <p>Número do Pedido: <strong>@Model.PedidoId</strong></p>

            <table class="table">
                <tr>
                    <th></th>
                    <th>Quantidade</th>
                    <th>Lanche</th>
                    <th>Preço</th>
                </tr>
                @foreach (var item in Model.PedidoItens)
                {
                    <tr>
                        <td><img src="@item.Lanche.ImagemUrl" width="40" height="40" /></td>
                        <td>@item.Quantidade</td>
                        <td>@item.Lanche.Nome</td>
                        <td>@item.Lanche.Preco</td>
                    </tr>      
                }
            </table>

            <h4>Valor Total do Pedido: <strong>@(((decimal)ViewBag.TotalPedido).ToString("C2"))</strong></h4>

        </div>
    </div>
</div>

<div class="form-group" style="text-align: center">
    <h3>
        <a class="nav-link text-info" asp-controller="Home" asp-action="Index">Retornar</a>
    </h3>
</div>