LanchesMac/ViewModels/PedidoLancheViewModel.cs
using LanchesMac.Models;

namespace LanchesMac.ViewModels
{
    public class PedidoLancheViewModel
    {
        public Pedido Pedido { get; set; }
        public IEnumerable<PedidoDetalhe> PedidoDetalhes { get; set; }
    }
}

LanchesMac/Areas/Admin/Controllers/AdminPedidosController.cs
using LanchesMac.Context;
using LanchesMac.Models;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;

namespace LanchesMac.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminPedidosController : Controller
    {
        private readonly AppDbContext _context;

        public AdminPedidosController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult PedidoLanches (int? id)
        {
            var pedido = _context.Pedidos.Include(pd => pd.PedidoItens).ThenInclude(l => l.Lanche).FirstOrDefault(p => p.PedidoId == id);

            if (pedido == null)
            {
                Response.StatusCode = 404;
                return View("PedidoNotFound", id.Value);
            }

            PedidoLancheViewModel pedidoLanches = new PedidoLancheViewModel()
            {
                Pedido = pedido,
                PedidoDetalhes = pedido.PedidoItens
            };
            return View(pedidoLanches);
        }

        // GET: Admin/AdminPedidos
        //public async Task<IActionResult> Index()
        //{
        //      return View(await _context.Pedidos.ToListAsync());
        //}

        public async Task<IActionResult> Index(string filter, int pageindex = 1, string sort = "Nome")
        {
            var resultado = _context.Pedidos.AsNoTracking().AsQueryable();

            if (!string.IsNullOrWhiteSpace(filter))
            {
                resultado = resultado.Where(p => p.Nome.Contains(filter));
            }

            var model = await PagingList.CreateAsync(resultado, 5, pageindex, sort, "Nome");
            model.RouteValue = new RouteValueDictionary { { "filter", filter } };

            return View(model);
        }

        // GET: Admin/AdminPedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PedidoId,Nome,Sobrenome,Endereco1,Endereco2,Cep,Estado,Cidade,Telefone,Email,PedidoEnviado,PedidoEntregueEm")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Admin/AdminPedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PedidoId,Nome,Sobrenome,Endereco1,Endereco2,Cep,Estado,Cidade,Telefone,Email,PedidoEnviado,PedidoEntregueEm")] Pedido pedido)
        {
            if (id != pedido.PedidoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.PedidoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Admin/AdminPedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pedidos == null)
            {
                return Problem("Entity set 'AppDbContext.Pedidos'  is null.");
            }
            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido != null)
            {
                _context.Pedidos.Remove(pedido);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
          return _context.Pedidos.Any(e => e.PedidoId == id);
        }
    }
}

LanchesMac/Areas/Admin/Views/AdminPedidos/Create.cshtml
@model LanchesMac.Models.Pedido

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco1" class="control-label"></label>
                <input asp-for="Endereco1" class="form-control" />
                <span asp-validation-for="Endereco1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco2" class="control-label"></label>
                <input asp-for="Endereco2" class="form-control" />
                <span asp-validation-for="Endereco2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cep" class="control-label"></label>
                <input asp-for="Cep" class="form-control" />
                <span asp-validation-for="Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEnviado" class="control-label"></label>
                <input asp-for="PedidoEnviado" class="form-control" />
                <span asp-validation-for="PedidoEnviado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEntregueEm" class="control-label"></label>
                <input asp-for="PedidoEntregueEm" class="form-control" />
                <span asp-validation-for="PedidoEntregueEm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/Delete.cshtml
@model LanchesMac.Models.Pedido

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEnviado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEnviado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEntregueEm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEntregueEm)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PedidoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/Details.cshtml
@model LanchesMac.Models.Pedido

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEnviado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEnviado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEntregueEm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEntregueEm)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PedidoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/Edit.cshtml
@model LanchesMac.Models.Pedido

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PedidoId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco1" class="control-label"></label>
                <input asp-for="Endereco1" class="form-control" />
                <span asp-validation-for="Endereco1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco2" class="control-label"></label>
                <input asp-for="Endereco2" class="form-control" />
                <span asp-validation-for="Endereco2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cep" class="control-label"></label>
                <input asp-for="Cep" class="form-control" />
                <span asp-validation-for="Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEnviado" class="control-label"></label>
                <input asp-for="PedidoEnviado" class="form-control" />
                <span asp-validation-for="PedidoEnviado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEntregueEm" class="control-label"></label>
                <input asp-for="PedidoEntregueEm" class="form-control" />
                <span asp-validation-for="PedidoEntregueEm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LanchesMac/Areas/Admin/Views/AdminPedidos/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<LanchesMac.Models.Pedido>

@{
    ViewData["Title"] = "Index";
}

<h3>Pedidos</h3>

<form method="get" class="form-inline">
    <input name="filter" class="form-control" placeholder="filtro" value="@Model.RouteValue["Filter"]"/>
    <button type="submit" class="btn btn-info">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Procurar
    </button>
</form>

Total de Pedidos: @Model.TotalRecordCount
<div>
    <vc:pager paging-list="@Model"></vc:pager>
</div>

<p>
    <a asp-action="Create">Criar Novo Pedido</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endereco1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endereco2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cep)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PedidoEnviado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PedidoEntregueEm)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cep)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PedidoEnviado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PedidoEntregueEm)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PedidoId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PedidoId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PedidoId">Delete</a> |
                <a asp-action="PedidoLanches" asp-route-id="@item.PedidoId">Ver Itens</a>
            </td>
        </tr>
}
    </tbody>
</table>

LanchesMac/Areas/Admin/Views/AdminPedidos/PedidoLanches.cshtml
@model LanchesMac.ViewModels.PedidoLancheViewModel

@{
    ViewData["Title"] = "PedidoLanches";
    decimal totalPedido = 0;
}

<h1>Lanche do Pedido</h1>
<hr />

<h3>Pedido: @Html.DisplayFor(model => @Model.Pedido.PedidoId)</h3>
<h3>Cliente: @Html.DisplayFor(model => @Model.Pedido.Nome)</h3>
<h3>Data: @Html.DisplayFor(model => @Model.Pedido.PedidoEnviado)</h3>
<h3>Entrega: @Html.DisplayFor(model => @Model.Pedido.PedidoEntregueEm)</h3>

<table class="table">
    @foreach (var item in Model.Pedido.PedidoItens)
    {
        totalPedido += (item.Lanche.Preco * item.Quantidade);

        <tr>
            <td align="right">
                <h3>@Html.DisplayFor(modelItem => item.Lanche.Nome)</h3>
            </td>
            <td align="right">
                <img src="@item.Lanche.ImagemUrl" class="img-fluid" height="100" width="100">
            </td>
            <td align="right">
                <h3>@string.Format("{0:C}", item.Lanche.Preco)</h3>
            </td>
            <td align="right">
                <h3>@Html.DisplayFor(modelItem => item.Quantidade)</h3>
            </td>
        </tr>
    }
    <tr>
        <td colspan="2">&nbsp;</td>
        <td align="right">
            <h3>Total do Pedido: @string.Format("{0:C}", @totalPedido)</h3>
        </td>
    </tr>
</table>
<a asp-action="Index" class="btn btn-outline-info">Retornar</a>

LanchesMac/Areas/Admin/Views/AdminPedidos/PedidoNotFound.cshtml
@model int

@{
    ViewData["Title"] = "404 Not Found";
}

<div class="alert alert-danger mt-1 bm-1">
    <h1>Erro 404 - Not Found</h1>
    <hr />
    <h2>
        Pedido com o id = @Model não foi encontrado
    </h2>
</div>

<a asp-action="Index" asp-controller="AdminPedidos" class="btn btn-outline-success">
    <h2>Retornar para a lista de Pedidos</h2>
</a>